#!/usr/bin/env python3
"""Fan out and fan in the chess-tracker fleet.

The main host runs nginx, the site, and its own workers. A fanned-out node is
the same image with nginx switched off -- it serves the site on 8081 and runs
its own workers, and nginx on main balances across all of them.

Nodes are deliberately self-contained. Nothing is shared: the gallery and models
are read-only and identical, the job queue is ephemeral and per-node, and the
live WebSocket handles cannot be shared at all -- a result computed on node B
has to be pushed down a socket node A is holding, which is why the balancer
hashes on CF-Connecting-IP and why the queue must NOT move to a shared database.

The only state worth keeping is the append-only record: finished games and
"it's me" claims. Fan-in merges those into main before destroying a node, which
is the whole reason fan-in is a command and not just a delete.

    ./deploy/fleet.py status
    ./deploy/fleet.py fanout 2        # add two nodes
    ./deploy/fleet.py fanin 1         # merge and remove one
    ./deploy/fleet.py fanin all       # back to main only
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vultr as V                                            # noqa: E402

MAIN_LABEL = "chess-prod"
NODE_PREFIX = "chess-node"
NODE_PLAN = "vhp-4c-8gb-amd"
REGION = "ewr"
SITE_PORT = 8081
SSH = ("ssh -o BatchMode=yes -o StrictHostKeyChecking=no "
       "-o UserKnownHostsFile=/dev/null -o ConnectTimeout=10")


def sh(host, cmd, timeout=300):
    """Run a script on a host, passed over stdin.

    Not as an argv string: the nginx config is full of $variables, and quoting
    them through a local shell, ssh, and a remote shell expands them somewhere
    in the middle. `bash -s` with the script on stdin has no quoting layer at
    all -- the first version of this silently wrote a config with every nginx
    variable blanked out, and reported success.
    """
    r = subprocess.run(f"{SSH} root@{host} bash -s", shell=True, input=cmd,
                       capture_output=True, text=True, timeout=timeout)
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def instances():
    ins = V.api("/instances").get("instances", [])
    main = next((i for i in ins if i.get("label") == MAIN_LABEL), None)
    nodes = sorted((i for i in ins if (i.get("label") or "").startswith(NODE_PREFIX)),
                   key=lambda i: i["label"])
    return main, nodes


# ---------------------------------------------------------------- balancer --
def write_upstream(main_ip, node_ips):
    """Write the whole balancer config and reload.

    The whole file, not a regex substitution into it. The first version matched
    an `upstream ... }` block and silently did nothing when it failed to match,
    reporting "reloaded with 3 backends" while the config still listed one --
    every request went to main and the fan-out looked like it had no effect.
    A generated file cannot half-apply.
    """
    backends = "\n".join(
        [f"    server 127.0.0.1:{SITE_PORT} max_fails=2 fail_timeout=10s;"]
        + [f"    server {ip}:{SITE_PORT} max_fails=2 fail_timeout=10s;"
           for ip in node_ips])
    conf = f"""# GENERATED by deploy/fleet.py -- edits here are overwritten on the next
# fan-out or fan-in.
#
# Affinity is not optional. A WebSocket is one TCP connection pinned to one
# backend for its whole life, so the socket path would survive any balancing
# method -- but the HTTP fallback submits a job in one request and polls
# /api/job/<id> in the next, and a job lives in the queue of the node that
# accepted it. Land the poll elsewhere and the visitor waits forever for a job
# that box never heard of.
#
# Hash on CF-Connecting-IP, not $remote_addr: Cloudflare is in front, so
# $remote_addr is a Cloudflare edge and every visitor behind one edge would
# clump onto a single node. `consistent` is ketama, so adding or removing a
# node reshuffles about 1/N of visitors instead of all of them -- which is what
# makes fan-out cheap rather than disruptive.
upstream chess_nodes {{
    hash $http_cf_connecting_ip consistent;
{backends}
}}

server {{
    listen 8080;
    server_name _;

    # A 1+0 game holds its socket for the whole game and the visitor may sit on
    # the results panel afterwards; the client pings every 45 s.
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    location / {{
        proxy_pass http://chess_nodes;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
    }}
}}
"""
    script = f"""cat > /etc/nginx/sites-available/chess-lb.conf <<'NGINXEOF'
{conf}NGINXEOF
n=$(grep -c '^    server ' /etc/nginx/sites-available/chess-lb.conf)
if nginx -t >/dev/null 2>&1; then
  systemctl reload nginx && echo "reloaded, $n backend(s) in config"
else
  echo "NGINX CONFIG BAD - not reloaded"; nginx -t 2>&1 | tail -2; exit 1
fi
"""
    rc, out, err = sh(main_ip, script)
    # Trust the file, not the intent: report what is actually in it.
    want = 1 + len(node_ips)
    if f"{want} backend(s)" not in out:
        print(f"  WARNING: expected {want} backends, balancer says: {out or err}")
    return rc, out, err


def allow_node(main_ip, node_ip):
    """Let a node reach main's site port, and main reach the node's."""
    sh(main_ip, f"ufw allow from {node_ip} to any port {SITE_PORT} proto tcp >/dev/null")
    sh(node_ip, f"ufw allow from {main_ip} to any port {SITE_PORT} proto tcp >/dev/null")


# ------------------------------------------------------------------ fanout --
FIRST_BOOT = f"""
set -e
# nginx belongs to main only; a node just serves.
systemctl disable --now nginx >/dev/null 2>&1 || true
# The snapshot carries main's databases. Start empty so fan-in merges real rows
# rather than re-importing main's own history back into main.
systemctl stop chess-id chess-move-worker@1 chess-move-worker@2 chess-identify-worker@1 >/dev/null 2>&1 || true
rm -f /opt/chess-id/jobs.db* /opt/chess-id/games.db*
: > /opt/chess-id/repo/play/claims.jsonl
systemctl start chess-id
for i in $(seq 1 90); do
  [ "$(curl -s -m 2 -o /dev/null -w '%{{http_code}}' localhost:{SITE_PORT}/healthz)" = "200" ] && break
  sleep 2
done
systemctl start chess-move-worker@1 chess-move-worker@2 chess-identify-worker@1
echo node-ready
"""


def fanout(n):
    main, nodes = instances()
    if not main:
        sys.exit("no main host")
    V.guard_hours(n * 0.0658, 2.0)
    snap = open("/tmp/chess_snap_id.txt").read().strip()
    key = V.ssh_key_id("~/.ssh/id_ed25519.pub")
    used = {int(i["label"].rsplit("-", 1)[-1]) for i in nodes
            if i["label"].rsplit("-", 1)[-1].isdigit()}
    made = []
    for _ in range(n):
        k = next(x for x in range(1, 99) if x not in used)
        used.add(k)
        i = V.api("/instances", "POST",
                  {"region": REGION, "plan": NODE_PLAN, "snapshot_id": snap,
                   "label": f"{NODE_PREFIX}-{k}", "hostname": f"{NODE_PREFIX}-{k}",
                   "sshkey_id": [key], "backups": "disabled"})["instance"]
        made.append(i["id"])
        print(f"  creating {NODE_PREFIX}-{k}")
    ips = []
    for iid in made:
        inst = V.wait_active(iid, timeout=600)
        ips.append(inst["main_ip"])
        print(f"  {inst['label']} booted at {inst['main_ip']}")
    for ip in ips:
        for _ in range(60):
            if sh(ip, "true", timeout=20)[0] == 0:
                break
            time.sleep(6)
        allow_node(main["main_ip"], ip)
        rc, out, err = sh(ip, FIRST_BOOT, timeout=600)
        print(f"  {ip}: {'ready' if 'node-ready' in out else 'FAILED ' + err[:120]}")
    _, nodes = instances()
    write_upstream(main["main_ip"], [i["main_ip"] for i in nodes])
    print(f"  balancer now fronts {1 + len(nodes)} node(s)")


# ------------------------------------------------------------------- fanin --
def node_claim_lines(ip):
    rc, out, _ = sh(ip, "wc -l < /opt/chess-id/repo/play/claims.jsonl 2>/dev/null || echo 0")
    try:
        return int(out.strip() or 0)
    except ValueError:
        return 0


def merge_claims(main_ip, node_ip, label):
    """Append a node's claim events to main's log and make them live.

    Verbatim, not replayed through /api/claim: each event carries the rank the
    account had AT THE TIME it was claimed, computed server-side against that
    node's gallery. Re-posting would recompute it against main and quietly
    rewrite the one number that makes a claim usable as a labelled eval case.

    Returns (added_events, ok).
    """
    want = node_claim_lines(node_ip)
    if not want:
        return 0, True
    local = f"/tmp/{label}_claims.jsonl"
    r1 = subprocess.run(f"scp -q {SSH.replace('ssh ', '')} "
                        f"root@{node_ip}:/opt/chess-id/repo/play/claims.jsonl {local}",
                        shell=True, capture_output=True, text=True)
    if r1.returncode:
        return 0, False
    r2 = subprocess.run(f"scp -q {SSH.replace('ssh ', '')} {local} "
                        f"root@{main_ip}:/tmp/node_claims.jsonl",
                        shell=True, capture_output=True, text=True)
    if r2.returncode:
        return 0, False
    before = node_claim_lines(main_ip)
    rc, out, err = sh(main_ip, """
set -e
C=/opt/chess-id/repo/play/claims.jsonl
# Append, never overwrite: this file IS the record, and main's own claims are
# already in it.
cat /tmp/node_claims.jsonl >> $C
rm -f /tmp/node_claims.jsonl
# The log is only read at boot, so tell the running process to replay it.
. /opt/chess-id/worker.env
curl -s -m 20 -X POST -H "Content-Type: application/json" \
  -H "X-Worker-Token: $WORKER_TOKEN" \
  http://127.0.0.1:8081/api/worker/reload-claims
echo
""")
    after = node_claim_lines(main_ip)
    ok = (after - before) == want and '"ok": true' in out.lower()
    return want, ok


def node_game_count(ip):
    rc, out, _ = sh(ip, "python3 -c \"import sqlite3;"
                        "c=sqlite3.connect('/opt/chess-id/games.db');"
                        "print(c.execute('select count(*) from games').fetchone()[0])\" "
                        "2>/dev/null || echo 0")
    try:
        return int(out.strip() or 0)
    except ValueError:
        return 0


MERGE = """
python3 - <<'PYEOF'
import sqlite3, os, sys
src, dst = '/tmp/node_games.db', '/opt/chess-id/games.db'
if not os.path.exists(src):
    print('MERGE-FAILED no file at ' + src); sys.exit(1)
d = sqlite3.connect(dst); d.execute("PRAGMA busy_timeout=10000")
d.execute("ATTACH ? AS n", (src,))
cols = [r[1] for r in d.execute("PRAGMA table_info(games)")][1:]   # drop id
cl = ",".join(cols)
# Ids are per-node autoincrement and would collide, so main assigns new ones.
n = d.execute(f"INSERT INTO games({cl}) SELECT {cl} FROM n.games").rowcount
d.commit()
print(f'MERGED {n}')
PYEOF
rm -f /tmp/node_games.db
"""


def fanin(n):
    """Drain, merge, VERIFY, then destroy -- in that order, and not otherwise.

    The first version copied the node's database with an scp launched from main,
    swallowed the error, and destroyed the node anyway: three games went in and
    "merged 0 games (node had none)" came out. A node is the only copy of the
    games played on it, so nothing here may proceed on an unchecked assumption.
    The copy goes via this machine, which has keys to both, and the row count is
    compared before and after. A node whose games did not land is left running.
    """
    main, nodes = instances()
    if not nodes:
        print("no nodes to remove")
        return
    victims = nodes[-n:] if n != "all" else nodes
    keep = [i["main_ip"] for i in nodes if i not in victims]
    # Out of the balancer FIRST, so nothing new lands on a node being drained.
    write_upstream(main["main_ip"], keep)
    print(f"  removed {len(victims)} node(s) from the balancer; draining 20s")
    time.sleep(20)

    for v in victims:
        ip, label = v["main_ip"], v["label"]
        want = node_game_count(ip)
        before = node_game_count(main["main_ip"])
        if want:
            local = f"/tmp/{label}_games.db"
            # Via this machine: main cannot ssh to a node cloned from main's own
            # snapshot, because main's public key is not in its own
            # authorized_keys. That is what failed silently the first time.
            r1 = subprocess.run(f"scp -q {SSH.replace('ssh ', '')} "
                                f"root@{ip}:/opt/chess-id/games.db {local}",
                                shell=True, capture_output=True, text=True)
            r2 = subprocess.run(f"scp -q {SSH.replace('ssh ', '')} "
                                f"{local} root@{main['main_ip']}:/tmp/node_games.db",
                                shell=True, capture_output=True, text=True)
            if r1.returncode or r2.returncode:
                print(f"  {label}: COPY FAILED, leaving it running "
                      f"({(r1.stderr or r2.stderr)[:90]})")
                continue
            rc, out, err = sh(main["main_ip"], MERGE, timeout=180)
            after = node_game_count(main["main_ip"])
            if "MERGED" not in out or after - before != want:
                print(f"  {label}: MERGE UNVERIFIED ({before} -> {after}, "
                      f"expected +{want}) -- leaving it running")
                continue
            print(f"  {label}: merged {want} games ({before} -> {after})")
        else:
            print(f"  {label}: no games to merge")

        # Claims are the only ground truth this demo ever collects -- everywhere
        # else it is guessing. Losing them to a fan-in would be worse than
        # losing the games.
        n_claims, ok = merge_claims(main["main_ip"], ip, label)
        if not ok:
            print(f"  {label}: CLAIMS MERGE FAILED -- leaving it running")
            continue
        print(f"  {label}: merged {n_claims} claim event(s)")

        sh(main["main_ip"],
           f"ufw delete allow from {ip} to any port {SITE_PORT} proto tcp >/dev/null")
        V.destroy(v["id"])
        print(f"  {label}: destroyed")


def status():
    main, nodes = instances()
    print(f"main  {main['label'] if main else '(none)'}  {main['main_ip'] if main else ''}")
    if main:
        rc, out, _ = sh(main["main_ip"],
                        "grep -c 'server .*:%d' /etc/nginx/sites-available/chess-lb.conf" % SITE_PORT)
        print(f"  balancer fronts {out} backend(s)")
    for i in nodes:
        rc, out, _ = sh(i["main_ip"],
                        f"curl -s -m 3 -o /dev/null -w '%{{http_code}}' localhost:{SITE_PORT}/healthz")
        print(f"  {i['label']:16s} {i['main_ip']:16s} health {out}")
    V.spend()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    cmd = sys.argv[1]
    if cmd == "status":
        status()
    elif cmd == "fanout":
        fanout(int(sys.argv[2]))
    elif cmd == "fanin":
        fanin("all" if sys.argv[2] == "all" else int(sys.argv[2]))
    elif cmd == "lb":
        m, ns = instances()
        print(write_upstream(m["main_ip"], [i["main_ip"] for i in ns])[1])
    else:
        sys.exit(f"unknown command {cmd}")
